### ISSUE TITLE
Importing vertex normals from s3o

### ISSUE THREAD

**Issue by Beherith** [sanguinariojoe/blender_s3o_import#8]
Blender seems to import normals correctly on first look, as the mesh has correct normals on import. But once you click edit (or even on export) the normals information is lost :(

**Comment by Beherith** [comment]
Should I provide some examples and details on how to reproduce? I tried looking at blenders .obj importer script, that can import normals correctly, but it was too complex for me :(

**Comment by sanguinariojoe** [comment]
It shall be fixed by [this](https://github.com/sanguinariojoe/blender_s3o_import/commit/679ff8daeaf89a45f4e98c7acffd665ecd4dd1a3) (I messed up with the issue index though)

In summary, the normals are just prefect. For me is clearly an upspring issue, which is artificially duplicating vertices, something Blender does not stands for... However, since there are many broken upspring models around there, I'm doing the upspring guys job and adding a tool to remove such duplicated vertices :-p
